import 'establishment.dart';

class Autogenerated {
  String username;
  String password;
  String name;
  String email;
  String acessLevel;
  bool status;
  Establishment establishment;

  Autogenerated(
      {this.username,
      this.password,
      this.name,
      this.email,
      this.acessLevel,
      this.status,
      this.establishment});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    username = json['username'];
    password = json['password'];
    name = json['name'];
    email = json['email'];
    acessLevel = json['acessLevel'];
    status = json['status'];
    establishment = json['establishment'] != null
        ? new Establishment.fromJson(json['establishment'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['username'] = this.username;
    data['password'] = this.password;
    data['name'] = this.name;
    data['email'] = this.email;
    data['acessLevel'] = this.acessLevel;
    data['status'] = this.status;
    if (this.establishment != null) {
      data['establishment'] = this.establishment.toJson();
    }
    return data;
  }
}